# Generated by Django 5.2.3 on 2025-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(default=None),
        ),
    ]
